name: release new version

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore Packages
        run: nuget restore BroadcastPlugin.sln
      - name: Build
        run: msbuild BroadcastPlugin.sln -p:Configuration=release
